-- MySQL Script generated by MySQL Workbench
-- Tue Aug 19 14:49:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forum_collège_maisonneuve
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forum_collège_maisonneuve
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum_collège_maisonneuve` DEFAULT CHARACTER SET utf8 ;
USE `forum_collège_maisonneuve` ;

-- -----------------------------------------------------
-- Table `forum_collège_maisonneuve`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum_collège_maisonneuve`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `forum_collège_maisonneuve`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum_collège_maisonneuve`.`Utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `nom_utilisateur` VARCHAR(50) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `date_naissance` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_utilisateur_UNIQUE` (`nom_utilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum_collège_maisonneuve`.`Forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum_collège_maisonneuve`.`Forum` (
  `id_forum` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `article` TEXT NOT NULL,
  `date_creation` DATE NOT NULL,
  `Utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id_forum`),
  INDEX `fk_Forum_Utilisateur_idx` (`Utilisateur_id` ASC),
  CONSTRAINT `fk_Forum_Utilisateur`
    FOREIGN KEY (`Utilisateur_id`)
    REFERENCES `forum_collège_maisonneuve`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
